<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Items;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'description' => 'ALCOHOL, Ethyl, 500ml',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bottle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ALCOHOL, Ethyl, 1 Gallon',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'gallon',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CLEARBOOK, A4 size',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CLEARBOOK, Legal size',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ERASER, plastic rubber',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Extra Fine Tip, Black',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Extra Fine Tip, Blue',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Extra Fine Tip, Red',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Fine Tip, Black',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Fine Tip, Blue',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Fine Tip, Red',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Medium Tip, Black',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Medium Tip, Blue',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SIGN PEN, Medium Tip, Red',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'WRAPPING PAPER',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'BATTERY, dry cell, size AA',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'BATTERY, dry cell, size AAA',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'AIR FRESHENER',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'can',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'BROOM (Walis Tambo)',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'BROOM (Walis Ting-ting)',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CLEANER, Toilet Bowl and Urinal',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bottle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CLEANSER, Scouring Powder',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'can',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'DETERGENT BAR',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'DETERGENT POWDER, all purpose',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pouch',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'DISINFECTANT SPRAY',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'can',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'DUST PAN',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FLOOR WAX, paste type, red',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'can',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FURNITURE CLEANER',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'can',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'HAND SOAP, liquid, 500ml',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bottle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'MOP BUCKET',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'unit',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'RAGS',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bundle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SCOURING PAD',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TRASH BAG, XXL size',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TRASHBAG, Large size',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TRASHBAG, XL size',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'WASTE BASKET',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'STAMP PAD, INK',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bottle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ACETATE',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'roll',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CARBON FILM, Legal size',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FIRE EXTINGUISHER, Dry Chemical',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'unit',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'GLUE, all-purpose',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bottle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'STAPLE WIRE, heavy duty (binder type), 23/13',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'STAPLE WIRE, standard',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TAPE, electrical',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'roll',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TAPE, masking, 24mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'roll',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TAPE, masking, 48mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'roll',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TAPE, packaging, 48mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'roll',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TAPE, transparent, 24mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'roll',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TAPE, transparent, 48mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'roll',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TWINE, plastic',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'roll',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'RULER, plastic, 450mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'BLADE, plastic, 450mm for general purpose cutter/utility knife',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'tube',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'BINDING AND PUNCHING MACHINE',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'unit',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'BINDING RING/COMB, plastic,32mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bundle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CALCULATOR, Compact',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'unit',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CHALK, white enamel',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CLIP, backfold, 19mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CLIP, backfold, 25mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CLIP, backfold, 32mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CLIP, backfold, 50mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CORRECTION TAPE',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CUTTER/UTILITY KNIFE, HEAVY DUTY',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'DATA FILE BOX',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'DATA FOLDER',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'DATER STAMP',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ENVELOPE, Documentary, A4 size',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ENVELOPE, Documentary, Legal size',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ENVELOPE, Expanding, Kraft',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ENVELOPE, Expanding, Plastic',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ENVELOPE, Mailing',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ENVELOPE, Mailing with window',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'ERASER, felt, for whiteboard/blackboard',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FASTENER, METAL, NON-SHARP EDGES',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FILE ORGANIZER',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FILE TAB DIVIDER, A4',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'set',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FILE TAB DIVIDER, Legal',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'set',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FOLDER, MOROCCO WITH SLIDE, A4',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bundle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FOLDER, MOROCCO WITH SLIDE, LEGAL',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bundle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FOLDER, L-TYPE, A4',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FOLDER, L-TYPE, Legal',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FOLDER, with tab, A4',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FOLDER, with tab, Legal',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'FOLDER, pressboard, Legal',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'INDEX TAB',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'Marker, Flourescent',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'set',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'Marker, Permanent, Black',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'Marker, Permanent, Blue',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'Marker, Permanent, Red',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'Marker, Whiteboard, Black',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'Marker, Whiteboard, Blue',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'Marker, Whiteboard, Red',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER CLIP, vinly/plastic coated, 33mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER CLIP, vinly/plastic coated jumbo, 50mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER SHREDDER',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'unit',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER TRIMMER/CUTTING MACHINE',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'unit',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PENCIL, lead/graphite, with eraser',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PENCIL SHARPENER',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PUNCHER, paper, heavy duty',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'RUBBER BAND No. 18',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'STAMP PAD, felt',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'SCISSORS, symmetrical/assymetrical',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pair',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'STAPLER, standard type',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'STAPLER, heavy duty (binder)',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'unit',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'STAPLE REMOVER, plier-type',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TAPE DISPENSER, table top',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'unit',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'CARTOLINA, assorted colors',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'COMPUTER CONTINUOUS FORM, 1 ply, 280mm x 241mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'COMPUTER CONTINUOUS FORM, 1 ply, 280mm x 378mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'NOTEPAD, stick-on, 50mm x 76mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pad',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'NOTEPAD, stick-on, 76mm x 100mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pad',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'NOTEPAD, stick-on, 76mm x 76mm',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pad',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'STENO NOTEBOOK',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'piece',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER, MULTICOPY A4',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'ream',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER, MULTICOPY LEGAL',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'ream',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER, MULTIPURPOSE A4',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'ream',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER, MULTIPURPOSE LEGAL',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'ream',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAD PAPER, ruled',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pad',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'PAPER, parchment',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'box',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'RECORD BOOK, 300 pages',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'book',
                'status' => 'in_stock',
                'image' => null,
            ],
                                    [
                'description' => 'RECORD BOOK, 500 pages',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'book',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TISSUE, INTERFOLDED PAPER TOWEL',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'TOILET TISSUE PAPER, 2-ply',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'pack',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'HAND SANITIZER',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'bottle',
                'status' => 'in_stock',
                'image' => null,
            ],
            [
                'description' => 'INSECTICIDE',
                'category_id' => null,
                'stock_quantity' => 1,
                'unit' => 'can',
                'status' => 'in_stock',
                'image' => null,
            ],
        ];

        foreach ($items as $item) {
            Items::create($item);
        }
    }
}